//! Codegen for m1-core. `cargo run -p xtask -- gen-kinds` regenerates
//! `m1-core/src/kind.rs` from the grammar's node-types.json.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Symbolic (non-identifier) token types mapped to enum variant names.
/// NOTE: `=` is `Assign` (not `Eq`) so it does not collide with the keyword
/// `eq` which becomes `Eq`. Adding a new operator to the grammar without an
/// entry here makes the generator panic — intentional, so the map stays complete.
const SYMBOL_MAP: &[(&str, &str)] = &[
    ("!", "Bang"), ("!=", "BangEq"), ("%", "Percent"), ("&", "Amp"),
    ("&&", "AmpAmp"), ("(", "LParen"), (")", "RParen"), ("*", "Star"),
    ("*=", "StarEq"), ("+", "Plus"), ("+=", "PlusEq"), (",", "Comma"),
    ("-", "Minus"), ("-=", "MinusEq"), (".", "Dot"), ("/", "Slash"),
    ("/=", "SlashEq"), (":", "Colon"), (";", "Semicolon"), ("<", "Lt"),
    ("<<", "LtLt"), ("<=", "LtEq"), ("=", "Assign"), ("==", "EqEq"),
    (">", "Gt"), (">=", "GtEq"), (">>", "GtGt"), ("?", "Question"),
    ("^", "Caret"), ("{", "LBrace"), ("|", "Pipe"), ("||", "PipePipe"),
    ("}", "RBrace"),
];

fn is_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut c = seg.chars();
            let first = c.next().unwrap().to_ascii_uppercase();
            format!("{first}{}", c.as_str())
        })
        .collect()
}

fn variant_name(ty: &str) -> String {
    if is_ident(ty) {
        pascal_case(ty)
    } else {
        SYMBOL_MAP
            .iter()
            .find(|(sym, _)| *sym == ty)
            .map(|(_, name)| name.to_string())
            .unwrap_or_else(|| panic!("no SYMBOL_MAP entry for token {ty:?}; add one in xtask"))
    }
}

/// Produce the full contents of `src/kind.rs` from a node-types.json string.
pub fn generate_kind_rs(node_types_json: &str) -> String {
    let parsed: serde_json::Value =
        serde_json::from_str(node_types_json).expect("node-types.json must be valid JSON");
    let entries = parsed.as_array().expect("node-types.json must be an array");

    // Distinct node type strings, sorted for deterministic output.
    let mut types: BTreeMap<String, ()> = BTreeMap::new();
    for e in entries {
        if let Some(t) = e.get("type").and_then(|v| v.as_str()) {
            types.insert(t.to_string(), ());
        }
    }

    // (variant_name, type_string), sorted by variant name; detect collisions.
    let mut variants: Vec<(String, String)> = types
        .keys()
        .map(|ty| (variant_name(ty), ty.clone()))
        .collect();
    variants.sort();
    for pair in variants.windows(2) {
        assert!(
            pair[0].0 != pair[1].0,
            "two node types map to variant {:?}: {:?} and {:?}",
            pair[0].0, pair[0].1, pair[1].1
        );
    }

    let mut out = String::new();
    out.push_str("// @generated by `cargo run -p xtask -- gen-kinds`. Do not edit by hand.\n");
    out.push_str("//! Typed node kinds for the M1 grammar, generated from node-types.json.\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum Kind {\n");
    for (variant, _) in &variants {
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("    /// A node type not known when this file was generated.\n");
    out.push_str("    Other,\n");
    out.push_str("}\n\n");
    out.push_str("impl Kind {\n");
    out.push_str("    /// Map a tree-sitter kind string to a [`Kind`].\n");
    out.push_str("    pub fn from_kind_str(s: &str) -> Kind {\n");
    out.push_str("        match s {\n");
    for (variant, ty) in &variants {
        out.push_str(&format!("            {ty:?} => Kind::{variant},\n"));
    }
    out.push_str("            _ => Kind::Other,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn kind_rs_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/kind.rs")
}

fn main() {
    let generated = generate_kind_rs(tree_sitter_m1::NODE_TYPES_JSON);
    let path = kind_rs_path();
    std::fs::write(&path, generated).expect("write src/kind.rs");
    println!("wrote {}", path.display());
}

#[cfg(test)]
mod tests {
    #[test]
    fn kind_rs_is_fresh() {
        let expected = super::generate_kind_rs(tree_sitter_m1::NODE_TYPES_JSON);
        let actual = std::fs::read_to_string(super::kind_rs_path())
            .expect("src/kind.rs must exist — run `cargo run -p xtask -- gen-kinds`");
        assert_eq!(
            actual, expected,
            "src/kind.rs is stale; run `cargo run -p xtask -- gen-kinds`"
        );
    }
}
