// @generated by `cargo run -p xtask -- gen-kinds`. Do not edit by hand.
//! Typed node fields for the M1 grammar, generated from node-types.json.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Field {
    Alternative,
    Arguments,
    Body,
    Condition,
    Consequence,
    End,
    Function,
    Left,
    Name,
    Object,
    Operator,
    Pattern,
    Property,
    Right,
    Start,
    State,
    Subject,
    Target,
    Type,
    TypeAnnotation,
    Value,
    Variable,
}

impl Field {
    /// The grammar field-name string, for tree-sitter lookups.
    pub fn as_str(self) -> &'static str {
        match self {
            Field::Alternative => "alternative",
            Field::Arguments => "arguments",
            Field::Body => "body",
            Field::Condition => "condition",
            Field::Consequence => "consequence",
            Field::End => "end",
            Field::Function => "function",
            Field::Left => "left",
            Field::Name => "name",
            Field::Object => "object",
            Field::Operator => "operator",
            Field::Pattern => "pattern",
            Field::Property => "property",
            Field::Right => "right",
            Field::Start => "start",
            Field::State => "state",
            Field::Subject => "subject",
            Field::Target => "target",
            Field::Type => "type",
            Field::TypeAnnotation => "type_annotation",
            Field::Value => "value",
            Field::Variable => "variable",
        }
    }
}
